### ISSUE TITLE
Problem with rendering $public_key

### ISSUE THREAD

**Issue by ZsharE** [greggilbert/recaptcha#101]
I set in config/recaptcha.php
```
'public_key'    => env('RECAPTCHA_PUBLIC_KEY'),
'private_key'    => env('RECAPTCHA_PRIVATE_KEY')
```

I added in env:
```
RECAPTCHA_PUBLIC_KEY=xxx
RECAPTCHA_PRIVATE_KEY=yyy
```

After i go to the registration page, i get in console this error:
```
Missing required parameters in RecaptchaOptions: sitekey
```

Also the captcha is not rendered and the html tag is looking like this:
```
<div class="g-recaptcha" data-sitekey=""></div>
```

Then i go to vendor/greggilbert/recaptcha/src/views/captchav2.blade.php to see exactly why attribute "data-sitekey" is empty and i saw that the public key is echoed: {{ $public_key }}, but is not rendering. So i changed "{{ $public_key }}" with "{{ env('RECAPTCHA_PUBLIC_KEY') }}". Now the captcha is rendering but after validation and submit i receive this error:
```
Please ensure that you are a human!
```

Why do you think the $public_key is not rendered and where i need to change to make it working ? I really don't understand, i updated to your latest version and i'm using Laravel 5.1.7.

**Comment by DigitalCoder** [comment]
Hi ! 

Did you resolved this pb ?

I've got the same :(

**Comment by ZsharE** [comment]
Yes, i solved it by generating a new laravel app key.

**Comment by greggilbert** [comment]
So.. this doesn't sound like something wrong with the package. As such, closing.
