### ISSUE TITLE
Should validation rule be implicit?

### ISSUE THREAD

**Issue by skyrpex** [greggilbert/recaptcha#108]
Currently, the validation rule is created using

```php
$this->app->validator->extendImplicit()
```

This forces me use the bail rule (```'g-recaptcha-response' => 'bail|required|recaptcha',```) in order to not get two validation messages when the user doesn't click the Recaptcha thingy.

I think that the rule shouldn't be implicit for this reason. Maybe I'm wrong, but solves my use case in a cleaner way.

**Comment by greggilbert** [comment]
I guess it's a question of how complete the validator error reporting should be. `extendImplicit` gets full results. I think I'm going to leave it as is, since the `bail` solution works.
