### ISSUE TITLE
"Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by IceBlackSanctum** [greggilbert/recaptcha#109]
Hi,

During the installation I had the following error:
illuminate/support v5.2.25 requires illuminate/contracts 5.3.* -> satisfiable by illuminate/contracts[5.3.x-dev] but these conflict with your requirements or minimum-stability.

Here my composer.json

> {
        "name": "laravel/laravel",
        "description": "The Laravel Framework.",
        "keywords": ["framework", "laravel"],
        "license": "MIT",
        "type": "project",
        "require": {
                "laravel/framework": "5.0.*",
                "greggilbert/recaptcha": "dev-master"
        },
        "require-dev": {
                "phpunit/phpunit": "~4.0",
                "phpspec/phpspec": "~2.1"
        },
        "autoload": {
                "classmap": [
                        "database"
                ],
                "psr-4": {
                        "App\\": "app/"
                }
        },
        "autoload-dev": {
                "classmap": [
                        "tests/TestCase.php"
                ]
        },
        "scripts": {
                "post-install-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-update-cmd": [
                        "php artisan clear-compiled",
                        "php artisan optimize"
                ],
                "post-create-project-cmd": [
                        "php -r \"copy('.env.example', '.env');\"",
                        "php artisan key:generate"
                ]
        },
        "config": {
                "preferred-install": "dist"
        }
}

Do you have some idea to resolve that problem ?

Regards,

**Comment by greggilbert** [comment]
Since you're doing this: `"laravel/framework": "5.0.*",`, presumably you want to use Laravel 5.0. In that case, use the latest 2.0 branch.
