### ISSUE TITLE
getting "Please ensure that you are a human!" message

### ISSUE THREAD

**Issue by shahreare** [greggilbert/recaptcha#110]
hi,
i am getting "Please ensure that you are a human!" message even after giving correct answer in the recaptcha field.

i am using version 2 of recaptcha and laravel 5.2
validation rule
`'g-recaptcha-response' => 'required|recaptcha'`

rendering captcha using
`{!! Recaptcha::render() !!}`

**Comment by marioevel** [comment]
Hello, I am getting the same error as @shahreare. I did a composer update after to see if anything had changed but it didn't make a difference. It had been working perfectly before.

**Comment by greggilbert** [comment]
I just tested locally using the latest master (fb835b2) and it seems to be working just fine. Questions to help debug:

* Which driver are you using - curl or native?
* Can you dump out the raw response from your validator? 
* In the package's CheckRecaptchaV2.php, can you dump out `$checkResponse`?

**Comment by shahreare** [comment]
thanks for reply.
in response to your reply...

- i am using curl
- `dd($validator->messages());` shows following data
```
MessageBag {#211 ▼
  #messages: array:1 [▼
    "g-recaptcha-response" => array:1 [▼
      0 => "Please ensure that you are a human!"
    ]
  ]
  #format: ":message"
}
```

- and get checkResponse value `false` when dumping it after this line

`$checkResponse = curl_exec($curl);`

**Comment by greggilbert** [comment]
After the `$checkResponse` line, add this: `dd(curl_error($curl));`. What's the output from that?

**Comment by shahreare** [comment]
solved the problem after changing 'curl_timeout' value to 10.

**Comment by jonjie0317** [comment]
Same issue here, but Im not using curl, hmm what should I do with this?

**Comment by BAKTETE** [comment]
After the `$checkResponse` line, adding this: `dd(curl_error($curl));` show this :
"SSL certificate problem: unable to get local issuer certificate"
