### ISSUE TITLE
Please ensure that you are a human! Yes I've tried updating curl_timeout ;-)

### ISSUE THREAD

**Issue by mbaxter91288** [greggilbert/recaptcha#115]
Hi,

No matter what I always get the following response:

`Please ensure that you are a human!`

The front end seems to validate ok but the backend validation never succeeds. I have tried the following:

* changed `curl_timeout` setting to 10
* changed `curl_timeout` setting to 100
* changed driver to native
* removed all composer files and reinstalled
* tried various versions of this package (it seems anything prior to 2.1 doesn't play ball with Laravel 5.1?)

This was working perfectly with Laravel 5.0 and version 2.0.0 but since updating to Laravel 5.1 (this has been updated because I use October CMS which has just released a new version including 5.1) and being forced to use 2.1 and up (due to conflict with illuminate/support) it only returns above response.

I have a few websites using this so if I could cheekily ask for any urgency with some troubleshooting that would be appreciated :)

Regards,
Mat

**Comment by valk96** [comment]
+1 same problem

**Comment by greggilbert** [comment]
@valk96: what's wrong with that line?

@mbaxter91288: The package works fine. Check your server and make sure it can actually make outgoing requests, and things like that.

**Comment by phpspider** [comment]
Change from
'options' => [

        'curl_timeout' => 10,
        'curl_verify' => true,
    ],

to 

'options' => [

        'curl_timeout' => 10,
        'curl_verify' => false,

    ],

**Comment by jonjie0317** [comment]
@phpspider is it safe to make `curl_verify` to **false**?

**Comment by phpspider** [comment]
@jonjie0317 It's not safe but on your local machine you can go with this.

**Comment by jonjie0317** [comment]
@phpspider how about for the production?

**Comment by phpspider** [comment]
@jonjie0317  On production it should work automatically i.e. always will be true. So no worry about that. If it's not then please check your server as @greggilbert mentioned previously.
https://github.com/greggilbert/recaptcha/issues/115#issuecomment-246894100
