### ISSUE TITLE
extend vs extendImplicit?

### ISSUE THREAD

**Issue by jmp909** [greggilbert/recaptcha#118]
is there a reason `extendImplicit` is used?

I don't want to run the recaptcha check if it has not been supplied

eg with `extend` the recaptcha check would not run when using `required|recaptcha` if I don't complete the recaptcha. it will just fail due to the `required`

because `extendImplicit` is used, then both rules run and 2 errors are returned

* The g-recaptcha-response field is required.
* Please ensure that you are a human!

theoretically both aren't required as they mean the same thing?

thanks
J

**Comment by jmp909** [comment]
actually I've just noticed if you set both responses the same then only one is shown

```php
'g-recaptcha-response.required' => 'Please complete the captcha',
'g-recaptcha-response.recaptcha' => 'Please complete the captcha',
```

**Comment by greggilbert** [comment]
No particular reason `extendImplicit` is being used. There is a semantic difference between `required` and `recaptcha`, though, namely that the first is whether or not there is a value in the box, and the second is whether or not that value is _valid_.
