### ISSUE TITLE
validator not working

### ISSUE THREAD

**Issue by moeinrahimi** [greggilbert/recaptcha#124]
hi
google recaptcha show up correctly but it doesn't matter if i check the recaptcha or not, validator not working
i'm using latest branch version 2.1-dev .

**Comment by greggilbert** [comment]
Check your validation rules; as best as I can tell, this is not an issue with the package.

**Comment by moeinrahimi** [comment]
you are right, where should i put this validation rules ? i'm using laravel default authentication system.
