### ISSUE TITLE
Validation Fails

### ISSUE THREAD

**Issue by adhranjan** [greggilbert/recaptcha#138]
Everything seems perferct but when when i subbmit the form it validator doesnt validate g-recaptcha-response...

**Comment by farhadkb6868** [comment]
I have the same problem. Laravel doesn't pass validation rules when I use reCatpcha.
any idea?

**Comment by rvwoens** [comment]
same here

**Comment by EliZaicheTest** [comment]
I had the same problem and as stupid as it sounds my problem was solved by replacing {!! Recaptcha::render() !!} with ```<div class="g-recaptcha" data-sitekey="your_site_key"></div>``` Hope that will help you.

**Comment by pawel-dubiel** [comment]
Also, check logs for curl errors.  In my case in local environment, i was receiving silently this error "CURL error: SSL certificate problem: unable to get local issuer certificate"

you can disable this by setting curl_verify=false in config/recaptcha.php

**Comment by nanadjei2** [comment]
Getting the same issue

**Comment by nanadjei2** [comment]
This solution works https://m.dotdev.co/google-recaptcha-integration-with-laravel-ad0f30b52d7d
