### ISSUE TITLE
Any plan to add support for Laravel 6.0?

### ISSUE THREAD

**Issue by daveatpeta** [greggilbert/recaptcha#164]

**Comment by hebinet** [comment]
I would love to see that too!

Should be an easy fix.

Just change to following line in `composer.json` to:
```js
"illuminate/support": "~5.1||~6.0"
```

**Comment by greggilbert** [comment]
Folks, I'm sorry to do this, but I've marked this package as abandoned. I don't have time to maintain it. PR #165 covers this, though, so you might want to look at that to get immediate coverage for L6.

**Comment by hebinet** [comment]
Hi Greg,

can please mark the package in packagist as abandoned so everybody notice it right away?
I found no clue that this package is abandoned in github.
