### ISSUE TITLE
How to refresh captcha if we are using ajax post.

### ISSUE THREAD

**Issue by hironate** [greggilbert/recaptcha#18]
Thanks for the nice module

I am using your module. i want to validate recaptcha on ajax request. but how to refresh captcha if captcha it's not validated.

Response will be appreciated.

**Comment by mansouralex** [comment]
@greggilbert Hi, does this way still applicable these days?

Thanks.

**Comment by rebootcode** [comment]
You can reset recaptcha using below code in your javascript :- 

```
gcaptcha.reset();
```
