### ISSUE TITLE
Multiple recaptcha on one page

### ISSUE THREAD

**Issue by ghost** [greggilbert/recaptcha#27]
Hi is it possible to use 2 recaptcha on one page in two different forms?

**Comment by amirkheirabadi** [comment]
hi ...
yes i have problem like this ....
how put two recaptch in one page ....????

**Comment by greggilbert** [comment]
The [official documentation](https://developers.google.com/recaptcha/docs/display) has answers on how to do this. You'd have to bypass the `Form::captcha()` stuff and render it on your own via Javascript. The lines in the validator should be the same, though.
