### ISSUE TITLE
async javascript

### ISSUE THREAD

**Issue by xavadu** [greggilbert/recaptcha#29]
Hello,

What about to call the javascript file with async?, 
so the script is non-blocking the page load

`<script type="text/javascript" async src="//www.google.com/recaptcha/api/challenge?k=<?php echo $public_key ?><?php echo (isset($lang) ? '&hl='.$lang : '') ?>"></script>`

or add an option to allow async

Cheers,
J.

**Comment by greggilbert** [comment]
Sorry, this is a limitation in how the reCAPTCHA works overall. See the official docs.
