### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by ZondLV** [greggilbert/recaptcha#42]
This does not work:
{{ Form::captcha(array('options' => array('lang' => $language ) ) ) }}

**Comment by greggilbert** [comment]
Does it throw an error? Is $language defined? I need a bit more to go on here.

**Comment by ZondLV** [comment]
I have localization (bla.com/en, bla.com/lv). 
$language is 'en' or 'lv'. But captcha still shows only in default language defined in config.

**Comment by greggilbert** [comment]
The first parameter is a list of options. Try:

`{{ Form::captcha(array('lang' => $language ) ) }}`
