### ISSUE TITLE
Problem after a while of working (RecaptchaServiceProvider)

### ISSUE THREAD

**Issue by mmatecki** [greggilbert/recaptcha#46]
Hi,
I've got very strange problem on one site using your library.
After uploading to server everything works well, after a few minutes (random) it stops. I've got exception: production.ERROR: exception 'ErrorException' with message 'trim() expects parameter 1 to be string, array given' at /vendor/greggilbert/recaptcha/src/Greggilbert/Recaptcha/RecaptchaServiceProvider.php:80

However if I upload RecaptchaServiceProvider again to server it starts to work again for a while.
I compared the RecaptchaServiceProvider before and after issue and it's the same!
Any ideas what could be wrong?
Thanks in advance for assistance.
Regards,
Maciej Matecki

**Comment by greggilbert** [comment]
Huh, that's really strange. The line that's throwing that error is reading from the config. Do you have the `template` line in the config set to something other than a string?

**Comment by mmatecki** [comment]
Hi,
Yes there's for sure everything configured correctly. I believe that there's issue with server configuration. I've got Laravel page on another server and there's everything ok.
I received the logs from administrator and there's such information:
CRASH: PHP bus error compiling /web_site/vendor/greggilbert/recaptcha/src/Greggilbert/Recaptcha/RecaptchaServiceProvider.php

**Comment by kjbstar** [comment]
Hello,

I had the same problem (on Laravel 4.2).
Even with the recaptcha html hardcoded in the form, I still had validation issues (g-recaptcha-response field is correct).

After a while, the only way I found to solve the issues was to put the configuration values in my app.php (in a "recaptcha" array), and in the package files, to replace every
app('config')->get('recaptcha::
by
app('config')->get('app.recaptcha.
