### ISSUE TITLE
Method validateCaptcha Does Not Exist

### ISSUE THREAD

**Issue by MineSQL** [greggilbert/recaptcha#50]
Hello,

Getting a fatal error thrown when validating a captcha. 

```
BadMethodCallException
Method [validateCaptcha] does not exist.
```

I added the correct provider to my app/config/app.php and displaying the captcha works fine. 

Thanks in advance.

**Comment by greggilbert** [comment]
Is this for L4 or L5?

**Comment by MineSQL** [comment]
This is for laravel 4.

**Comment by vDk3** [comment]
I have same issue and i am using version 1.1.5 for laravel 4 can you help me with this?
