### ISSUE TITLE
ErrorException in Recaptcha.php line 26: array_merge(): Argument #1 is not an array

### ISSUE THREAD

**Issue by elsodev** [greggilbert/recaptcha#53]
Hi,
I'm using laravel 5 and wanted to use Recaptcha2.

I have installed it but it seems php artisan vendor:publish does nothing. I do not see recaptcha config in my config folder.

Btw when I use  {!! Recaptcha::render() !!}

This error is shown:
ErrorException in Recaptcha.php line 26:
array_merge(): Argument #1 is not an array

Kindly check. Thank you.

**Comment by elsodev** [comment]
Looks like config/recaptcha.php of the package must be in our main config folder, im not sure why my artisan vendor:publish not doing anything but I copied the one in this package and pasted into my main config folder, it works now.

**Comment by greggilbert** [comment]
Good catch. I just pushed a change. Update the package, then try publishing and see if that moved the config in place. If it didn't, reopen this ticket. Thanks!
