### ISSUE TITLE
recaptcha always return wrong in validation ...

### ISSUE THREAD

**Issue by amirkheirabadi** [greggilbert/recaptcha#56]
hi
i use recaptcha 1.1.5 with laravel 4 and this work fine ...
but on inputs validation return that recaptcha is wrong ...
how i can fix this ???

**Comment by greggilbert** [comment]
Check to make sure you have the fields named properly in everything. I don't know what your code looks like, but as few people have had the issue, I believe it's beyond the scope of reporting an issue here.
