### ISSUE TITLE
Method [validateCaptcha] does not exist

### ISSUE THREAD

**Issue by vDk3** [greggilbert/recaptcha#57]
Hello,
I have following issue:

'BadMethodCallException' with message 'Method [validateCaptcha] does not exist.' in /vendor/laravel/framework/src/Illuminate/Validation/Validator.php:2547

I am using 1.1.5 version for laravel 4, can you help me with this?

**Comment by greggilbert** [comment]
Did you add the service provider into `app.php`?

**Comment by vDk3** [comment]
Yes, I added this line into providers array
'Greggilbert\Recaptcha\RecaptchaServiceProvider',
