### ISSUE TITLE
Improvement: readme.md

### ISSUE THREAD

**Issue by iLLogical2007** [greggilbert/recaptcha#59]
Although you included the info that Laravel 4.x users have to use the old 1.x branch, you removed the information how to display the captcha on that version. 

I checked if you could use the following function in Larvavel 4.2

```
{{ Recaptcha::render() }}
```

but it didn't work. Maybe you should add the advice in your Readme.md that Laravel 4.x users / Branch 1.x users have to use the old function

```
{{ Form::captcha() }}
```

to get their pages working.

**Comment by greggilbert** [comment]
If you go to the 1.x tags, such as [this](https://github.com/greggilbert/recaptcha/tree/1.1.5), the directions are there.
