### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by socieboy** [greggilbert/recaptcha#62]
It's not really a issue someone can help me? I got this error?

ErrorException in CheckRecaptchaV2.php line 41:
file_get_contents(): SSL: Connection reset by peer

**Comment by greggilbert** [comment]
That's weird. Did you try using `curl` instead?

**Comment by socieboy** [comment]
yes

2015-04-13 19:42 GMT-07:00 Greg <notifications@github.com>:
