### ISSUE TITLE
Recaptcha Issue

### ISSUE THREAD

**Issue by kameshveera** [greggilbert/recaptcha#70]
I  have a laravel 5 . I got following error  '[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Greggilbert\Recaptcha\RecaptchaServiceProvider' not found'  when run this command "php artisan vendor:publish".

**Comment by greggilbert** [comment]
Add the service provider into your config before you publish.

**Comment by hff135** [comment]
I had this problem too and it took me a while to figure it out.

The solution is to make the composer.json changes first and then run "composer update".  After that, make the changes to config/app.php.  Finally, run the "php artisan vendor:publish" command.

**Comment by Fedchishina** [comment]
@hff135 , thank you very much!!!

**Comment by woenel** [comment]
@hff135 Works pretty well. Thanks a lot.
