### ISSUE TITLE
recaptcha not displaying

### ISSUE THREAD

**Issue by TravisBrennan** [greggilbert/recaptcha#71]
recaptcha is not displaying in the form. when you view the source it shows it was implemented but the data-sitekey attribute it empty.

I did fill them in, in the config.

**Comment by greggilbert** [comment]
Did you ever figure this out?

**Comment by Perfect7M** [comment]
I got the same problem i dont know why

**Comment by jamiepgs** [comment]
I'm also getting this issue. Even tried manually putting the key into the view files and it still comes up empty. I've tried just manually putting the snippet from Google in, but then it doesn't pass validation.

**Comment by jamiepgs** [comment]
I've managed to resolve the issue for myself. I noticed another section of the view file that tries to pull the information from the config, so replaced that. Still doesn't validate, but managed to fix that by removing the curl method and just using file_get_contents. I'm guessing more a server issue, but I'm not bothered about looking into that right now - this will do for now.

**Comment by jryd** [comment]
I'm having the same issue too, when using {!! Recaptcha::render() !!} nothing appears on page.
When looking at the source no datakey is present, which is odd as I've defined it in the recaptcha file.

**Comment by jryd** [comment]
I managed to solve this. There is a recaptcha file for the keys stored in the config and vendor directories. Having it written in both seemed to solve my troubles.

**Comment by greggilbert** [comment]
Yes, you need to publish the config file for anything to really happen.

**Comment by andrewwindfall** [comment]
Currently having this issue. 
I have my composer all updated, published vendor, ran php artisan vendor:publish --provider="Greggilbert\Recaptcha\RecaptchaServiceProvider", keys set in both config and vendor directories, however still displaying on my form without a data-sitekey. 

I am missing something, I just don't know what. Any more advice?
Note: tried changing recaptcha to version 1 and it DOES recognize that my keys are for version 2. So there is some kind of recognition of my keys, it just isn't making it to the form!
