### ISSUE TITLE
Illuminate/support

### ISSUE THREAD

**Issue by silviolleite** [greggilbert/recaptcha#76]
When i try the command composer update  its shows me an error 

Illuminate/support require php version >=5.5.9 your php version does not satisfy that requirement 

and the problems shows too that recaptcha dev-master  require illumunate/suport ~5.1 

I am using Laravel 5.0 and php version 5.4.36

**Comment by greggilbert** [comment]
Did you read the directions? Use `greggilbert/recaptcha/tree/2.0.2`.
