### ISSUE TITLE
Javscript disabled - Fallback issue

### ISSUE THREAD

**Issue by Kryptonit3** [greggilbert/recaptcha#79]
When I disable JS to test plugin, the fallback HTML code isnt rendered

![img](http://i.snag.gy/xou8n.jpg)

Page in question - https://larabin.com/register (and others that use the code)

**Comment by greggilbert** [comment]
Hmm. I just tried and got this. Is this not correct?

![screen shot 2015-07-13 at 10 04 28 am](https://cloud.githubusercontent.com/assets/169482/8651408/a50aa3c4-2946-11e5-8ec6-d08c2e9801e0.png)
