### ISSUE TITLE
Can't add provider and aliases

### ISSUE THREAD

**Issue by asivaneswaran** [greggilbert/recaptcha#80]
Greggilbert\Recaptcha\RecaptchaServiceProvider::class
and
'Recaptcha' => Greggilbert\Recaptcha\Facades\Recaptcha::class,

Is not working. I replaced with: Greggilbert\Recaptcha\RecaptchaServiceProvider and 'Recaptcha' => Greggilbert\Recaptcha\Facades\Recaptcha but it gives me: array_merge(): Argument #1 is not an array
because $this->config = null.

**Comment by greggilbert** [comment]
Hmm, that's weird. Doesn't really strike me as an issue with the plugin. Did you publish the config?

**Comment by asivaneswaran** [comment]
Oups I thought I replied here. It was weird. I removed it from composer and re-did the install and it worked just fine. Real weird.
