### ISSUE TITLE
Invalid Response

### ISSUE THREAD

**Issue by dashracer** [greggilbert/recaptcha#93]
Hi, I've been using this library for a while now and there is no problem, but suddenly starting this morning, the capcha validation always fail. I don't know what the problem is.

**Comment by dharmendrajadon** [comment]
It stopped working on all my websites.

**Comment by greggilbert** [comment]
I just tried it out and it seemed fine. Can you give me some details about what you're seeing - errors, e.g.?

**Comment by dashracer** [comment]
There is no error. Just this message "The g-recaptcha-response field is not correct." 
That message always show even if I answer the capcha correctly
![fireshot screen capture 009 ](https://cloud.githubusercontent.com/assets/2896774/10760616/f8e64bf4-7cef-11e5-91bb-ba49b452b077.png)

**Comment by dharmendrajadon** [comment]
Any progress on the issue?
All of my websites are on stack!

**Comment by greggilbert** [comment]
Sorry, but I'm not able to replicate the bug. Has anything changed in your server config? Can you check the logs and see if there's anything in there? Go into the plugin and dump out the response from Google? I need something to go on.

**Comment by dashracer** [comment]
Hi greg, I've checked the log and there is this chunk of error message

```
[2015-10-28 10:23:54] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148
Stack trace:
#0 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 /home3/putrafa/public_html/smash.genetik.co.id/smashlaravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 /home3/putrafa/public_html/smash.genetik.co.id/public/v2/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
```
I don't know what it means

I also try to debug the plugin in checkrecapchav2 an v1 .php

this is what i got in curl $checkResponse variable

```
string '{
  "success": true
}' (length=21)
```
and the "The g-recaptcha-response field is not correct." sill shows up

**Comment by dharmendrajadon** [comment]
Its working on my VPN server but not on shared server. The same scripts, everything same.

**Comment by Hendriksie** [comment]
Hi,

I just used this component for the first time and it works perfectly.

I think it has to do with your own config, recheck the public and private keys you registered at google.

Best Regards,

Wesley Hendriks

**Comment by dharmendrajadon** [comment]
Nothing changed on websites. I have a dozen of websites running same code. It was working good until 2 days ago. I haven't changed anything on  any website in these two days. It suddenly stopped working. Invalid Response. That's it. But its working on one of my VPN hosted website. Not on Shared Hosting from Hostgator. I have many shared hosting accounts. None of them are working with Recaptcha.

**Comment by greggilbert** [comment]
@dashracer - the fact that it returned `success` means that the recaptcha is working, so my guess is that there's some other issue with your form or something like that.

@dharmendrajadon - what is saying "Invalid response"? Is that the `$checkResponse` value?

**Comment by dharmendrajadon** [comment]
I have figured it out. The reason behind all mass failure is that Hostgator did an update on servers and blocked all scripts. 

It has blocked even SMTP mail servers. You have to ask them to allow Google ReCaptcha script through their firewall. 

It will work. Good Luck.

@greggilbert Thank You for your support

**Comment by greggilbert** [comment]
Ouch. Well, that'll do it.

I'm going to close this ticket.
