### ISSUE TITLE
Loading Scripts from Google Server

### ISSUE THREAD

**Issue by jishadp** [greggilbert/recaptcha#94]
Hi Team,

Is there any option for loading scripts from Local directory other than Google Server . ?

Its taking too many time on sometime to load captcha.

Please reply as soon as possible.

**Comment by greggilbert** [comment]
Um, what? You mean the script tags? They're all loaded remotely; e.g. [here](https://github.com/greggilbert/recaptcha/blob/master/src/views/captchav2.blade.php#L19).
