### ISSUE TITLE
Still doesn't works with L5.1

### ISSUE THREAD

**Issue by Mdpproduction** [greggilbert/recaptcha#95]
i'm trying to install this package with l5.1, but doesn't works yet. Any suggestions ?

**Comment by greggilbert** [comment]
Wanna give me a bit more context?

**Comment by Mdpproduction** [comment]
Yes, excuse me, i forgot to copy and past the error. here is it:

**Could not find package at any version for your minimu stability**

i just use the command

**composer require gregglibert/recaptcha**

without any tag. I missed something ?

**Comment by greggilbert** [comment]
Well, you spelled the name wrong; it's `greggilbert/recaptcha`. If not that, I'd check what you have set for minimum stability in your `package.json`.

**Comment by Mdpproduction** [comment]
Was my fault. Sorry Greg. Works fine with L5.1

**Comment by jonjie0317** [comment]
Where is that part of your installation in the docs? the `composer require greggilbert/recaptcha` . I couldnt find it. Thanks
