### ISSUE TITLE
Validation doesn't function if the Input facade isn't aliased

### ISSUE THREAD

**Issue by Gawdl3y** [greggilbert/recaptcha#97]
If an application doesn't have the Input facade alias, the package's input validation will fail with an exception, due to the "Input" class not being resolvable in the IoC. Reliance upon a facade/alias is probably a bad idea for a package, since there's no guarantee they'll be present. Furthermore, Laravel 5.2's default config no longer includes the Input alias (see laravel/laravel@2adbbbd).

**Comment by 0plus1** [comment]
Thanks for the fix @Gawdl3y can you merge this change @greggilbert please?

**Comment by Gawdl3y** [comment]
Would you mind tagging a new release, @greggilbert?

**Comment by greggilbert** [comment]
@Gawdl3y So done.
